version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: custom-app
    ports:
      - "10003:8080"
    environment:
      API_MAIL_HOST: smtp4dev
      API_MAIL_PORT: 25
    depends_on:
      - smtp4dev
    networks:
      - internal

  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '3000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '2525:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    environment:
      - ServerOptions__HostName=smtp4dev
    networks:
      - internal

networks:
  internal:
    driver: bridge