# Database API
api.database.url=http://localhost:10001/api/v1/
api.database.endpoints.groups=groups
api.database.endpoints.events=events
api.database.endpoints.users=users
api.database.endpoints.notifications=notifications
api.database.endpoints.apps=apps

# Swagger
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/apidocs
springdoc.packages-to-scan=com.dynamiceventmanagement.notificationapp.controller