# Mail configuration
api.mail.host=localhost
api.mail.port=2525
api.mail.name=Custom App Notification
api.mail.email=no-reply@customapp.com

# Swagger
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/apidocs
springdoc.packages-to-scan=com.dynamiceventmanagement.customapp.controller