### Exceptions ###
# Data NotFound Exception
exception.data.not-found.generic=Data not found
exception.data.not-found.group=Group not found
exception.data.not-found.app=App not found
exception.data.not-found.app.notification-url=Notification URL in App not found
exception.data.not-found.event=Event not found
exception.data.not-found.notification=Notification not found
exception.data.not-found.user=User not found
exception.data.not-found.user.username=Username in User not found
# Data Integrity Exception
exception.data.integrity.generic=Data integrity exception
exception.data.integrity.app.name.empty=App name cannot be empty
exception.data.integrity.user.username.empty=User username cannot be empty
exception.data.integrity.user.username.exists=User username already exists
exception.data.integrity.group.app-id.empty=Group appId cannot be empty
exception.data.integrity.group.name.empty=Group name cannot be empty
exception.data.integrity.group.user-ids.empty=Group user ids cannot be empty
exception.data.integrity.group.name.exists=Group name already exists
exception.data.integrity.event.group-id.empty=Event groupId cannot be empty
exception.data.integrity.event.user-id.empty=Event userId cannot be empty
exception.data.integrity.notification.event-id.empty=Notification eventId cannot be empty
exception.data.integrity.notification.user-id.empty=Notification userId cannot be empty
exception.data.integrity.notification.user-id-to-notify.empty=Notification userIdToNotify cannot be empty
# Data Duplicate Key Exception
exception.data.duplicate-Key.generic=Data already exists
# Generic Exception
exception.generic=Generic exception